StringLiterals:
  EnforcedStyle: single_quotes

HashSyntax:
  Description: >
                 Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax
                 { :a => 1, :b => 2 }.
  EnforcedStyle: ruby19
  Enabled: true

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - bin/*
    - Rakefile
    - Gemfile
    - cloud_storage.gemspec
    - lib/concerns/*

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 120

Style/EndOfLine:
  Enabled: false

Style/AsciiComments:
  Enabled: false